# Generated by Django 2.1 on 2018-08-12 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('longbow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingPassingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='longbow.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='TestPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('completion_time', models.DateTimeField(null=True)),
                ('stat_correct_answers', models.PositiveIntegerField(default=0, null=True)),
                ('stat_count_answers', models.PositiveIntegerField(default=0, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='longbow.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestPassingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='longbow.Question')),
                ('test_passing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longbow.TestPassing')),
            ],
        ),
        migrations.AddField(
            model_name='testingpassinganswer',
            name='test_passing_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longbow.TestPassingQuestion'),
        ),
    ]
