# Generated by Django 2.1 on 2018-08-12 23:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('longbow', '0002_auto_20180812_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testpassing',
            unique_together={('test', 'user')},
        ),
    ]
