# Generated by Django 2.1 on 2018-08-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longbow', '0004_auto_20180813_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestingPassingAnswer',
            new_name='TestPassingAnswer',
        ),
    ]
